export enum Role {
  STS_MANAGER = 'STS MANAGER',
  ADMIN = 'ADMIN',
  UNASSIGNED = 'UNASSIGNER',
  LANDFILL_MANAGER = 'LANDFILL MANAGER',
}

export enum Permission {
  LEAD_READ = 'Lead-READ',
  LEAD_WRITE = 'Lead-WRITE',
  USER_MANAGEMENT_READ = 'USER-READ',
  USER_MANAGEMENT_WRITE = 'USER MANAGEMENT-WRITE',
  ROLE_MANAGEMENT_READ = 'ROLE MANAGEMENT-READ',
  ROLE_MANAGEMENT_WRITE = 'ROLE MANAGEMENT-WRITE',
  STS_MANAGEMENT_READ = 'STS MANAGEMENT-READ',
  STS_MANAGEMENT_WRITE = 'STS MANAGEMENT-WRITE',
  LANDFILL_MANAGEMENT_READ = 'LANDFILL MANAGEMENT-READ',
  LANDFILL_MANAGEMENT_WRITE = 'LANDFILL MANAGEMENT-WRITE',
  VEHICLES_MANAGEMENT_READ = 'VEHICLES MANAGEMENT-READ',
  VEHICLES_MANAGEMENT_WRITE = 'VEHICLES MANAGEMENT-WRITE',
  LANDFILL_ADMIN_READ = 'LANDFILL ADMIN-READ',
  LANDFILL_ADMIN_WRITE = 'LANDFILL ADMIN-WRITE',
  STS_ADMIN_READ = 'STS ADMIN-READ',
  STS_ADMIN_WRITE = 'STS ADMIN-WRITE',
  VEHICLES_ADMIN_READ = 'VEHICLES ADMIN-READ',
  VEHICLES_ADMIN_WRITE = 'VEHICLES ADMIN-WRITE',
}
