export const dummyLeads = [
  {
    key: '1',
    fullName: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    createdAt: '2024-03-18',
    purpose: 'unknown',
    desiredCourse: 'gre',
    counsellor: 'Alice',
    source: 'Website',
    passport: 'Yes',
    destination: 'UK',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '2',
    fullName: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+9876543210',
    createdAt: '2024-03-19',
    purpose: 'unknown',
    desiredCourse: 'ielts-academic',
    counsellor: 'Bob',
    source: 'Referral',
    passport: 'No',
    destination: 'USA',
    leadStatus: 'Inactive',
    action: 'View Details',
  },
  {
    key: '3',
    fullName: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    phone: '+1122334455',
    createdAt: '2024-03-20',
    purpose: 'english-teaching',
    desiredCourse: 'pte',
    counsellor: 'Charlie',
    source: 'Advertisement',
    passport: 'Yes',
    destination: 'Canada',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '4',
    fullName: 'Emily Brown',
    email: 'emily.brown@example.com',
    phone: '+9988776655',
    createdAt: '2024-03-21',
    purpose: 'Migration',
    desiredCourse: 'oet',
    counsellor: 'Alice',
    source: 'Social Media',
    passport: 'Yes',
    destination: 'Australia',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '5',
    fullName: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '+1122334455',
    createdAt: '2024-03-22',
    purpose: 'study-abroad',
    desiredCourse: 'cambridge-english',
    counsellor: 'Bob',
    source: 'Website',
    passport: 'Yes',
    destination: 'Singapore',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '6',
    fullName: 'Emma Johnson',
    email: 'emma.johnson@example.com',
    phone: '+4455667788',
    createdAt: '2024-03-23',
    purpose: 'unknown',
    desiredCourse: 'gre',
    counsellor: 'Charlie',
    source: 'Advertisement',
    passport: 'Yes',
    destination: 'Germany',
    leadStatus: 'Inactive',
    action: 'View Details',
  },
  {
    key: '7',
    fullName: 'Sophia Williams',
    email: 'sophia.williams@example.com',
    phone: '+7788990011',
    createdAt: '2024-03-24',
    purpose: 'English Teaching',
    desiredCourse: 'oietc',
    counsellor: 'Alice',
    source: 'Referral',
    passport: 'Yes',
    destination: 'France',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '8',
    fullName: 'James Brown',
    email: 'james.brown@example.com',
    phone: '+1122334455',
    createdAt: '2024-03-25',
    purpose: 'Migration',
    desiredCourse: 'sat',
    counsellor: 'Bob',
    source: 'Social Media',
    passport: 'Yes',
    destination: 'Italy',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '9',
    fullName: 'Olivia Taylor',
    email: 'olivia.taylor@example.com',
    phone: '+9988776655',
    createdAt: '2024-03-26',
    purpose: 'Study Abroad',
    desiredCourse: 'english-foundation',
    counsellor: 'Charlie',
    source: 'Website',
    passport: 'Yes',
    destination: 'Spain',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '10',
    fullName: 'William Davis',
    email: 'william.davis@example.com',
    phone: '+4455667788',
    createdAt: '2024-03-27',
    purpose: 'Education',
    desiredCourse: 'toefl',
    counsellor: 'Alice',
    source: 'Advertisement',
    passport: 'No',
    destination: 'Japan',
    leadStatus: 'Inactive',
    action: 'View Details',
  },
  {
    key: '11',
    fullName: 'Isabella Rodriguez',
    email: 'isabella.rodriguez@example.com',
    phone: '+7788990011',
    createdAt: '2024-03-28',
    purpose: 'English Teaching',
    desiredCourse: 'duolingo',
    counsellor: 'Bob',
    source: 'Referral',
    passport: 'Yes',
    destination: 'Sweden',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '12',
    fullName: 'Alexander Martinez',
    email: 'alexander.martinez@example.com',
    phone: '+1122334455',
    createdAt: '2024-03-29',
    purpose: 'unknown',
    desiredCourse: 'spoken',
    counsellor: 'Charlie',
    source: 'Social Media',
    passport: 'Yes',
    destination: 'Canada',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '13',
    fullName: 'Charlotte Wilson',
    email: 'charlotte.wilson@example.com',
    phone: '+9988776655',
    createdAt: '2024-03-30',
    purpose: 'Migration',
    desiredCourse: 'ielts-general',
    counsellor: 'Alice',
    source: 'Website',
    passport: 'Yes',
    destination: 'Australia',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '14',
    fullName: 'Michaela Brown',
    email: 'michaela.brown@example.com',
    phone: '+4455667788',
    createdAt: '2024-03-31',
    purpose: 'Study Abroad',
    desiredCourse: 'gre',
    counsellor: 'Bob',
    source: 'Referral',
    passport: 'Yes',
    destination: 'UK',
    leadStatus: 'Active',
    action: 'View Details',
  },
  {
    key: '15',
    fullName: 'Joshua Taylor',
    email: 'joshua.taylor@example.com',
    phone: '+7788990011',
    createdAt: '2024-04-01',
    purpose: 'Education',
    desiredCourse: 'oet',
    counsellor: 'Charlie',
    source: 'Social Media',
    passport: 'Yes',
    destination: 'New Zealand',
    leadStatus: 'Inactive',
    action: 'View Details',
  },
];
