export const dummyApplication = [
  {
    key: '1',
    lead: 'John Doe',
    course: 'Masters',
    intake_month: 'January',
    intake_year: 2023,
    university: 'Harvard',
    counsellor: 'Emma Watson',
    status: 'Applied',
    applied_on: '2024-03-15T09:30:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '2',
    lead: 'Alice Johnson',
    course: 'PhD',
    intake_month: 'February',
    intake_year: 2022,
    university: 'Oxford',
    counsellor: 'Michael Smith',
    status: 'Paid',
    applied_on: '2024-01-10T13:45:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '3',
    lead: 'Robert Brown',
    course: 'Pre-Masters',
    intake_month: 'March',
    intake_year: 2024,
    university: 'MIT',
    counsellor: 'Jessica Williams',
    status: 'Visa',
    applied_on: '2023-12-20T11:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '4',
    lead: 'Sarah Clark',
    course: '2nd Year',
    intake_month: 'April',
    intake_year: 2023,
    university: 'Stanford',
    counsellor: 'David Johnson',
    status: 'Enrolled',
    applied_on: '2024-02-05T14:20:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '5',
    lead: 'Michael Brown',
    course: '3rd Year',
    intake_month: 'May',
    intake_year: 2022,
    university: 'Cambridge',
    counsellor: 'Jennifer Davis',
    status: 'Enrolled',
    applied_on: '2024-04-01T10:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '6',
    lead: 'Emily Taylor',
    course: 'Masters',
    intake_month: 'June',
    intake_year: 2023,
    university: 'Yale',
    counsellor: 'Chris Evans',
    status: 'Applied',
    applied_on: '2024-03-28T16:50:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '7',
    lead: 'David Martinez',
    course: 'Top-up',
    intake_month: 'July',
    intake_year: 2024,
    university: 'Princeton',
    counsellor: 'Emma Thompson',
    status: 'Applied',
    applied_on: '2024-02-20T09:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '8',
    lead: 'Olivia Smith',
    course: 'Masters',
    intake_month: 'August',
    intake_year: 2024,
    university: 'Columbia',
    counsellor: 'Ryan Johnson',
    status: 'Paid',
    applied_on: '2024-01-05T10:15:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '9',
    lead: 'James Wilson',
    course: 'PhD',
    intake_month: 'September',
    intake_year: 2022,
    university: 'Caltech',
    counsellor: 'Emily Brown',
    status: 'Visa',
    applied_on: '2024-03-02T12:30:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '10',
    lead: 'Emma Clark',
    course: 'Pre-Masters',
    intake_month: 'October',
    intake_year: 2023,
    university: 'NYU',
    counsellor: 'Michael Brown',
    status: 'Enrolled',
    applied_on: '2023-11-11T15:40:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '11',
    lead: 'Daniel Johnson',
    course: '2nd Year',
    intake_month: 'November',
    intake_year: 2024,
    university: 'UCLA',
    counsellor: 'Jessica Taylor',
    status: 'Applied',
    applied_on: '2024-03-20T08:45:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '12',
    lead: 'Sophia Davis',
    course: '3rd Year',
    intake_month: 'December',
    intake_year: 2023,
    university: 'Imperial',
    counsellor: 'David Martinez',
    status: 'Paid',
    applied_on: '2024-02-10T11:20:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '13',
    lead: 'Ryan Johnson',
    course: 'Masters',
    intake_month: 'January',
    intake_year: 2022,
    university: 'UC Berkeley',
    counsellor: 'Olivia Smith',
    status: 'Visa',
    applied_on: '2023-12-30T14:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '14',
    lead: 'Isabella Wilson',
    course: 'Top-up',
    intake_month: 'February',
    intake_year: 2024,
    university: 'Northwestern',
    counsellor: 'James Wilson',
    status: 'Enrolled',
    applied_on: '2024-03-05T09:10:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '15',
    lead: 'Ethan Thomas',
    course: 'Masters',
    intake_month: 'March',
    intake_year: 2024,
    university: 'UCLA',
    counsellor: 'Sophia Clark',
    status: 'Applied',
    applied_on: '2024-02-15T10:30:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '16',
    lead: 'Mia Anderson',
    course: 'PhD',
    intake_month: 'April',
    intake_year: 2024,
    university: 'MIT',
    counsellor: 'William Davis',
    status: 'Paid',
    applied_on: '2024-01-20T12:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '17',
    lead: 'Lucas Martinez',
    course: 'Pre-Masters',
    intake_month: 'May',
    intake_year: 2023,
    university: 'Stanford',
    counsellor: 'Sophia Johnson',
    status: 'Visa',
    applied_on: '2024-03-25T15:20:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '18',
    lead: 'Sophia Clark',
    course: '2nd Year',
    intake_month: 'June',
    intake_year: 2023,
    university: 'Harvard',
    counsellor: 'Ethan Thomas',
    status: 'Enrolled',
    applied_on: '2023-12-10T17:45:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '19',
    lead: 'William Davis',
    course: '3rd Year',
    intake_month: 'July',
    intake_year: 2024,
    university: 'Yale',
    counsellor: 'Emily Taylor',
    status: 'Applied',
    applied_on: '2024-01-18T14:50:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '20',
    lead: 'Olivia Smith',
    course: 'Masters',
    intake_month: 'August',
    intake_year: 2022,
    university: 'Columbia',
    counsellor: 'Ryan Johnson',
    status: 'Paid',
    applied_on: '2023-11-28T11:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '21',
    lead: 'Michael Brown',
    course: 'PhD',
    intake_month: 'September',
    intake_year: 2023,
    university: 'Cambridge',
    counsellor: 'Jennifer Davis',
    status: 'Visa',
    applied_on: '2023-12-05T09:30:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '22',
    lead: 'Emma Clark',
    course: 'Pre-Masters',
    intake_month: 'October',
    intake_year: 2024,
    university: 'NYU',
    counsellor: 'Michael Brown',
    status: 'Enrolled',
    applied_on: '2024-02-20T13:45:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '23',
    lead: 'Daniel Johnson',
    course: '2nd Year',
    intake_month: 'November',
    intake_year: 2023,
    university: 'UCLA',
    counsellor: 'Jessica Taylor',
    status: 'Applied',
    applied_on: '2024-03-05T15:20:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '24',
    lead: 'Sophia Davis',
    course: '3rd Year',
    intake_month: 'December',
    intake_year: 2022,
    university: 'Imperial',
    counsellor: 'David Martinez',
    status: 'Paid',
    applied_on: '2023-11-10T08:00:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
  {
    key: '25',
    lead: 'Ryan Johnson',
    course: 'Masters',
    intake_month: 'January',
    intake_year: 2024,
    university: 'UC Berkeley',
    counsellor: 'Olivia Smith',
    status: 'Visa',
    applied_on: '2024-01-28T10:10:00',
    actions: ['<EditIcon />', '<DeleteIcon />'],
  },
];
