export const dummyActivities = [
  {
    key: '1',
    userType: 'Super Admin',
    activity: 'Login',
    activityDetails: 'Login Successfully',
    dateTime: '2024-04-01T09:30:00',
  },
  {
    key: '2',
    userType: 'Normal User',
    activity: 'Leads Download',
    activityDetails: 'Downloaded leads for analysis',
    dateTime: '2024-04-01T10:15:00',
  },
  {
    key: '3',
    userType: 'Editor',
    activity: 'Content Creation',
    activityDetails: 'Created a new article',
    dateTime: '2024-04-01T11:20:00',
  },
  {
    key: '4',
    userType: 'Customer Support',
    activity: 'Ticket Resolution',
    activityDetails: 'Resolved customer complaint #123',
    dateTime: '2024-04-01T13:45:00',
  },
  {
    key: '5',
    userType: 'Manager',
    activity: 'Report Generation',
    activityDetails: 'Generated monthly sales report',
    dateTime: '2024-04-01T15:00:00',
  },
  {
    key: '6',
    userType: 'Super Admin',
    activity: 'Leads Download',
    activityDetails: 'Downloaded leads for reporting',
    dateTime: '2024-04-02T10:30:00',
  },
  {
    key: '7',
    userType: 'Normal User',
    activity: 'Login',
    activityDetails: 'Login Successfully',
    dateTime: '2024-04-02T11:45:00',
  },
  {
    key: '8',
    userType: 'Editor',
    activity: 'Content Creation',
    activityDetails: 'Updated existing article',
    dateTime: '2024-04-02T12:10:00',
  },
  {
    key: '9',
    userType: 'Customer Support',
    activity: 'Ticket Creation',
    activityDetails: 'Created new support ticket #456',
    dateTime: '2024-04-02T14:20:00',
  },
  {
    key: '10',
    userType: 'Manager',
    activity: 'Approval',
    activityDetails: 'Approved leave request for employee',
    dateTime: '2024-04-02T16:30:00',
  },
  {
    key: '11',
    userType: 'Super Admin',
    activity: 'Login',
    activityDetails: 'Login Successfully',
    dateTime: '2024-04-03T09:30:00',
  },
  {
    key: '12',
    userType: 'Normal User',
    activity: 'Leads Download',
    activityDetails: 'Downloaded leads for marketing',
    dateTime: '2024-04-03T10:15:00',
  },
  {
    key: '13',
    userType: 'Editor',
    activity: 'Content Creation',
    activityDetails: 'Created a new blog post',
    dateTime: '2024-04-03T11:20:00',
  },
  {
    key: '14',
    userType: 'Customer Support',
    activity: 'Ticket Resolution',
    activityDetails: 'Resolved customer complaint #789',
    dateTime: '2024-04-03T13:45:00',
  },
  {
    key: '15',
    userType: 'Manager',
    activity: 'Report Generation',
    activityDetails: 'Generated quarterly financial report',
    dateTime: '2024-04-03T15:00:00',
  },
  {
    key: '16',
    userType: 'Super Admin',
    activity: 'Leads Download',
    activityDetails: 'Downloaded leads for outreach',
    dateTime: '2024-04-04T10:30:00',
  },
  {
    key: '17',
    userType: 'Normal User',
    activity: 'Login',
    activityDetails: 'Login Successfully',
    dateTime: '2024-04-04T11:45:00',
  },
  {
    key: '18',
    userType: 'Editor',
    activity: 'Content Creation',
    activityDetails: 'Updated existing blog post',
    dateTime: '2024-04-04T12:10:00',
  },
  {
    key: '19',
    userType: 'Customer Support',
    activity: 'Ticket Creation',
    activityDetails: 'Created new support ticket #1011',
    dateTime: '2024-04-04T14:20:00',
  },
  {
    key: '20',
    userType: 'Manager',
    activity: 'Approval',
    activityDetails: 'Approved purchase request for department',
    dateTime: '2024-04-04T16:30:00',
  },
];
